# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b57f6584d00e61b362b33cc276e2fb593c26ebe1f1e277ebde7d02634470ece60a5953e64e5a0a9fd0e76f132c848032a80d1e2de29d383e3ee13eeff546f711

test:
  secret_key_base: 6a10a5dda4b4a99f6a7621b6746df7016d8edd065cad3beaf7d269b83197fdb5a9f75fd12697e5b5aa2174a3a786f4e435a4a90e3b8536f9bfb4cc218f6b0cef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
